# Generated by Django 5.0.2 on 2024-09-05 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated',
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='Default Content'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
