# Generated by Django 5.0.2 on 2024-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_note_body_remove_note_updated_note_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
